## Project guide

- Use pnpm only.
- This is a React/Vite/MUI public website and CMS.
- Backend is Google Apps Script in apps-script/.
- Do not add mock content unless explicitly requested.
- Do not modify backend/admin when task is frontend-only.
- Do not modify frontend UI when task is backend-only.
- Prefer small diffs.
- Run pnpm quality before declaring success.

## Auto-generated signatures

<!-- Updated by gen-context.js -->
<!-- Generated by SigMap gen-context.js v6.10.0 -->
<!-- Updated: 2026-05-10T06:05:50.699Z -->
<!-- Do not edit below — regenerate with: node gen-context.js -->

## SigMap commands

| When                                   | Command                          |
| -------------------------------------- | -------------------------------- |
| Before answering a question about code | `sigmap ask "<your question>"`   |
| After changing config or source dirs   | `sigmap validate`                |
| To verify an AI answer is grounded     | `sigmap judge --response <file>` |

# Code signatures

## deps

```
src\public\components\home\HomeHeroSection.tsx ← ../../utils/safeUrl, DirectorHeroCard, ../../types
src\public\components\home\HomeIntroVideoSection.tsx ← HomeSectionHeading
src\public\components\home\JobOpportunitiesSection.tsx ← ../../utils/safeUrl, HomeSectionHeading
src\public\components\PublicIntroGate.tsx ← ../utils/safeUrl
src\public\components\PublicSiteShell.tsx ← PublicMainMenu, PublicErrorState, PublicLoadingState, FloatingMessengerButton, PublicIntroGate
src\public\pages\PublicHomePage.tsx ← ../services/siteSettings, ../types, components/PublicHomeCarousel, components/PublicSiteShell, components/home/AchievementHighlightsSection
src\admin\components\AdminActionProgress.tsx ← ../context/authSessionContext, ../services/googleApi
src\admin\components\ContentBlockBuilder.tsx ← ../types, ../utils/contentBlocks
src\admin\components\ContentEditorDialog.tsx ← ContentBlockBuilder, ../types, ../services/googleApi, ../utils/thaiLabels, ../utils/contentBlocks
src\admin\components\MetricCard.tsx ← ../types
src\admin\components\StatusChip.tsx ← ../types, ../utils/thaiLabels
src\admin\components\UserManagementCard.tsx ← ../context/authSessionContext, ../services/users, ../types, ../utils/swal, ../utils/thaiLabels
src\admin\layout\CmsShell.tsx ← ../config/projectSettings, ../context/authSessionContext, ../utils/swal
src\admin\pages\CalendarPage.tsx ← components/PageHeader, ../services/googleApi, ../types, ../utils/calendar, ../utils/dateDisplay
src\admin\pages\ContentPage.tsx ← components/ContentEditorDialog, components/PageHeader, components/StatusChip, ../services/googleApi, ../types
src\admin\pages\DashboardPage.tsx ← components/MetricCard, components/PageHeader, components/StatusChip, ../services/googleApi, ../utils/dateDisplay
src\admin\pages\IntegrationsPage.tsx ← components/PageHeader, components/StatusChip, ../config/projectSettings, ../services/googleApi, ../types
src\admin\pages\LoginPage.tsx ← ../config/projectSettings, ../context/authSessionContext, ../utils/swal
src\admin\pages\MediaPage.tsx ← components/PageHeader, ../services/googleApi, ../types, ../utils/dateDisplay, ../utils/swal
src\admin\pages\MenuPage.tsx ← components/PageHeader, ../services/googleApi, ../types, ../utils/swal
src\admin\pages\SettingsPage.tsx ← components/PageHeader, components/UserManagementCard, ../config/projectSettings, ../services/displaySettings, ../services/publicCmsCache
src\App.tsx ← context/AuthContext, config/projectSettings, routes, theme
src\config\projectSettings.ts ← project-settings, types
src\context\AuthContext.tsx ← config/projectSettings, types, services/auth, authSessionContext
src\context\authSessionContext.ts ← types
src\public\components\home\AchievementHighlightsSection.tsx ← HomeSectionHeading
src\public\components\home\ContactMapCard.tsx ← ../../types, ../../utils/safeUrl, HomeSectionHeading, homeSectionStyles
src\public\components\home\DirectorHeroCard.tsx ← ../../shared/components/EmptyState, ../../types, ../../utils/safeUrl
src\public\components\home\DocumentListCard.tsx ← ../../shared/components/EmptyState, ../../types, ../../utils/safeUrl, HomeSectionHeading, homeSectionStyles
src\public\components\home\EventListCard.tsx ← ../../shared/components/EmptyState, ../../types, ../../utils/dateDisplay, HomeSectionHeading
src\public\components\home\ExternalServicesSection.tsx ← ../../utils/safeUrl, HomeSectionHeading, homeSectionStyles
src\public\components\home\LatestAnnouncementsCard.tsx ← ../../shared/components/EmptyState, ../../types, ../../utils/dateDisplay, ../../utils/safeUrl, HomeSectionHeading
src\public\components\home\LatestNewsSection.tsx ← ../../utils/safeUrl, ../../types, ../../shared/components/EmptyState, PublicContentCard, HomeSectionHeading
src\public\components\home\ProcurementNewsSection.tsx ← ../../utils/safeUrl, HomeSectionHeading
src\public\components\home\ProgramsSection.tsx ← ../../types, ../../shared/components/EmptyState, PublicContentCard, HomeSectionHeading
src\public\components\PublicContentCard.tsx ← ../types, ../utils/dateDisplay, ../utils/safeUrl, ../utils/thaiLabels
src\public\components\PublicHomeCarousel.tsx ← ../utils/safeUrl
src\public\components\PublicLoadingState.tsx ← ../config/projectSettings
src\public\components\PublicMainMenu.tsx ← hooks/usePublicCmsSnapshot, ../types, ../utils/safeUrl
src\public\hooks\usePublicCmsSnapshot.ts ← ../services/googleApi, ../services/publicCmsCache
src\public\hooks\usePublicContentDetail.ts ← ../services/googleApi, ../services/publicCmsCache
src\public\pages\PublicAnnouncementsPage.tsx ← ../shared/components/EmptyState, components/PublicContentCard, components/PublicSiteShell, hooks/usePublicCmsSnapshot, ../utils/safeUrl
src\public\pages\PublicBlogPage.tsx ← ../shared/components/EmptyState, components/PublicContentCard, components/PublicSiteShell, hooks/usePublicCmsSnapshot
src\public\pages\PublicContactPage.tsx ← ../shared/components/EmptyState, ../services/siteSettings, ../utils/safeUrl, components/PublicSiteShell, hooks/usePublicCmsSnapshot
src\public\pages\PublicContentDetailPage.tsx ← ../shared/components/ContentBlocksRenderer, ../shared/components/EmptyState, ../services/googleApi, components/PublicContentCard, components/PublicSiteShell
src\public\pages\PublicDepartmentsPage.tsx ← ../shared/components/EmptyState, components/PublicContentCard, components/PublicSiteShell, hooks/usePublicCmsSnapshot
src\public\pages\PublicNewsPage.tsx ← ../shared/components/EmptyState, components/PublicContentCard, components/PublicSiteShell, hooks/usePublicCmsSnapshot, ../utils/safeUrl
src\routeComponents.tsx ← admin/components/AdminActionProgress, shared/components/VercelInsights, context/authSessionContext
src\services\auth.ts ← config/projectSettings, types, googleApi, users
src\services\displaySettings.ts ← config/projectSettings, types, googleApi
src\services\googleApi.ts ← config/projectSettings, types
src\services\publicCmsCache.ts ← types
src\services\siteSettings.ts ← types
src\services\users.ts ← config/projectSettings, types, googleApi
src\shared\components\ContentBlocksRenderer.tsx ← ../types, ../utils/contentBlocks, ../utils/safeUrl
src\utils\dateDisplay.ts ← types, services/displaySettings
src\utils\seo.ts ← config/projectSettings, safeUrl
```

## src

### src\public\components\FloatingMessengerButton.tsx

```
component FloatingMessengerButton
```

### src\public\components\home\HomeHeroSection.tsx

```
component HomeHeroSection
export HomeHeroSection
```

### src\public\components\home\HomeIntroVideoSection.tsx

```
component HomeIntroVideoSection
export HomeIntroVideoSection
```

### src\public\components\home\JobOpportunitiesSection.tsx

```
component JobOpportunitiesSection
export JobOpportunitiesSection
```

### src\public\components\home\UrgentMarqueeSection.tsx

```
component UrgentMarqueeSection
export UrgentMarqueeSection
```

### src\public\components\PublicIntroGate.tsx

```
component PublicIntroGate
hook useState
handler onClick
```

### src\public\components\PublicSiteShell.tsx

```
component TopBarInfoItem
component TopBarSocialIcons
component MobileTopBar
component DesktopTopBar
component FooterDirectory
component PublicSiteShell
props PublicSiteShellProps
props TopBarInfoItemProps
hook usePublicCmsSnapshot
hook useDocumentMetadata
handler onSubmit
handler onClick
```

### src\public\pages\PublicHomePage.tsx

```
component PublicHomePage
hook usePublicCmsSnapshot
hook useMemo
```

### src\admin\components\AdminActionProgress.tsx

```
component AdminActionProgress
hook useGoogleApiActivityCount
hook useSyncExternalStore
hook useAuth
hook useRouterState
hook useState
hook useRef
hook useEffect
```

### src\admin\components\ContentBlockBuilder.tsx

```
component ContentBlockBuilder
props ContentBlockBuilderProps
handler onChange
```

### src\admin\components\ContentEditorDialog.tsx

```
component ContentEditorDialog
props ContentEditorDialogProps
hook useState
hook useMemo
handler onClose
handler onSubmit
handler onChange
handler onInputChange
handler onKeyDown
handler onClick
```

### src\admin\components\MetricCard.tsx

```
component MetricCard
props MetricCardProps
hook useTheme
```

### src\admin\components\PageHeader.tsx

```
component PageHeader
props PageHeaderProps
```

### src\admin\components\StatusChip.tsx

```
component StatusChip
props StatusChipProps
```

### src\admin\components\UserManagementCard.tsx

```
component UserManagementCard
hook useAuth
hook useQueryClient
hook useQuery
hook useState
handler onClick
handler onClose
handler onChange
```

### src\admin\layout\CmsShell.tsx

```
component CmsShell
hook useState
hook useTheme
hook useMediaQuery
hook useNavigate
hook useRouterState
hook useAuth
```

### src\admin\pages\CalendarPage.tsx

```
component CalendarPage
hook useQueryClient
hook useQuery
hook useMemo
hook useState
hook useMutation
handler onClick
handler onChange
handler onClose
```

### src\admin\pages\ContentPage.tsx

```
component ContentPage
hook useQueryClient
hook useQuery
hook useState
hook useMemo
hook useMutation
hook useCallback
hook useReactTable
handler onClick
handler onChange
handler onSave
handler onUploadMedia
```

### src\admin\pages\DashboardPage.tsx

```
component DashboardPage
hook useQueryClient
hook useQuery
hook useMutation
hook useMemo
```

### src\admin\pages\IntegrationsPage.tsx

```
component IntegrationsPage
hook useQuery
```

### src\admin\pages\LoginPage.tsx

```
component LoginPage
hook useNavigate
hook useAuth
hook useState
handler onSubmit
handler onChange
```

### src\admin\pages\MediaPage.tsx

```
component MediaPage
hook useQueryClient
hook useQuery
hook useMemo
hook useState
hook useMutation
handler onClick
handler onChange
handler onClose
handler onSubmit
```

### src\admin\pages\MenuPage.tsx

```
component MenuTree
component MenuPage
props MenuTreeProps
hook useQueryClient
hook useQuery
hook useState
handler onAddChild
handler onEdit
handler onRemove
handler onMove
handler onClick
handler onClose
handler onChange
```

### src\admin\pages\SettingsPage.tsx

```
component SettingsPage
hook useQueryClient
hook useState
hook useQuery
hook useMutation
hook useMemo
handler onChange
```

### src\App.tsx

```
component App
```

### src\config\projectSettings.ts

```
export function getCmsSiteName()
export function getGoogleAppsScriptUrl()
export function getPublicSiteUrl()
```

### src\context\AuthContext.tsx

```
component AuthProvider
hook useState
hook useCallback
hook useMemo
export AuthProvider
```

### src\context\authSessionContext.ts

```
export interface AuthContextValue
  session: Session | null
  login: (email: string, password: string) =
  logout: () => void
export function useAuth()
```

### src\public\components\home\AchievementHighlightsSection.tsx

```
component AchievementHighlightsSection
export AchievementHighlightsSection
```

### src\public\components\home\ContactMapCard.tsx

```
component ContactMapCard
export ContactMapCard
```

### src\public\components\home\DirectorHeroCard.tsx

```
component DirectorHeroCard
export DirectorHeroCard
```

### src\public\components\home\DocumentListCard.tsx

```
component DocumentListCard
export DocumentListCard
```

### src\public\components\home\EventListCard.tsx

```
component EventListCard
export EventListCard
```

### src\public\components\home\ExternalServicesSection.tsx

```
component ExternalServicesSection
export ExternalServicesSection
```

### src\public\components\home\HomeSectionHeading.tsx

```
component HomeSectionHeading
props HomeSectionHeadingProps
export HomeSectionHeadingProps
export HomeSectionHeading
```

### src\public\components\home\LatestAnnouncementsCard.tsx

```
component CompactAnnouncementList
component LatestAnnouncementsCard
export LatestAnnouncementsCard
```

### src\public\components\home\LatestNewsSection.tsx

```
component LatestNewsSection
export LatestNewsSection
```

### src\public\components\home\ProcurementNewsSection.tsx

```
component ProcurementNewsSection
export ProcurementNewsSection
```

### src\public\components\home\ProgramsSection.tsx

```
component ProgramsSection
export ProgramsSection
```

### src\public\components\home\VisitorStatsCard.tsx

```
component VisitorStatsCard
export VisitorStatsCard
```

### src\public\components\PublicContentCard.tsx

```
component PublicContentCard
props PublicContentCardProps
```

### src\public\components\PublicErrorState.tsx

```
component PublicErrorState
props PublicErrorStateProps
handler onClick
```

### src\public\components\PublicHomeCarousel.tsx

```
component PublicHomeCarousel
hook useEmblaCarousel
hook useState
hook useCallback
hook useEffect
handler onObserver
handler onSelect
handler onClick
```

### src\public\components\PublicLoadingState.tsx

```
component PublicLoadingState
```

### src\public\components\PublicMainMenu.tsx

```
component PublicMenuList
component PublicTopLevelMenuMeasurement
component PublicMainMenu
component MobileMenuList
hook useTheme
hook useMediaQuery
hook usePublicCmsSnapshot
hook useMemo
hook useState
hook useRef
hook useCallback
hook useEffect
handler onClose
handler onClick
handler onNavigate
```

### src\public\hooks\usePublicCmsSnapshot.ts

```
export function usePublicCmsSnapshot()
```

### src\public\hooks\usePublicContentDetail.ts

```
export function usePublicContentDetail(input)
```

### src\public\pages\PublicAnnouncementsPage.tsx

```
component PublicAnnouncementsPage
hook usePublicCmsSnapshot
hook useMemo
```

### src\public\pages\PublicBlogPage.tsx

```
component PublicBlogPage
hook usePublicCmsSnapshot
hook useMemo
```

### src\public\pages\PublicContactPage.tsx

```
component LargeMapCard
component PublicContactPage
hook usePublicCmsSnapshot
```

### src\public\pages\PublicContentDetailPage.tsx

```
component PublicContentDetailPage
props PublicContentDetailPageProps
hook usePublicCmsSnapshot
hook usePublicContentDetail
hook useState
hook useMemo
hook useEffect
```

### src\public\pages\PublicDepartmentsPage.tsx

```
component PublicDepartmentsPage
hook usePublicCmsSnapshot
hook useMemo
```

### src\public\pages\PublicNewsPage.tsx

```
component PublicNewsPage
hook usePublicCmsSnapshot
hook useMemo
```

### src\routeComponents.tsx

```
component RouteFallback
component RootRouteLayout
component ProtectedLayout
component AdminOnlyPage
component PublicContentDetailRoute
hook useAuth
hook useParams
export CalendarPage
export CmsShell
export ContentPage
export DashboardPage
export IntegrationsPage
export LoginPage
export MediaPage
export MenuPage
export NotFoundPage
export PublicAnnouncementsPage
export PublicBlogPage
export PublicContactPage
export PublicContentDetailPage
export PublicDepartmentsPage
export PublicHomePage
export PublicNewsPage
export SettingsPage
export RouteFallback
```

### src\services\auth.ts

```
export async function hashPassword(password)
export async function login(email, password) → Promise<Session>
export function isTokenExpired(token, expiresAt?)
export function restoreSession(value) → Session | null
```

### src\services\displaySettings.ts

```
export function normalizeDisplaySettings(input) → DisplaySettings
export function getStoredDisplaySettings()
export async function loadDisplaySettings() → Promise<DisplaySettings>
export async function saveDisplaySettings(input) → Promise<DisplaySettings>
```

### src\services\googleApi.ts

```
export interface UserAccountInput
  id?: string
  name: string
  email: string
  role: UserAccount["role"]
  status: UserAccount["status"]
  password?: string
  passwordHash?: string
  avatarUrl?: string
export interface CalendarEventInput
  id?: string
  title: string
  date: string
  endDate?: string
  audience: string
  status: CalendarEvent["status"]
  location?: string
  description?: string
export interface MediaAssetInput
  id?: string
  name: string
  type: MediaType
  size?: string
  owner: string
  driveUrl?: string
```

### src\services\publicCmsCache.ts

```
export type CacheEntry
export function readPublicCache(key)
export function writePublicCache(key, data, ttlMs) → void
export function removePublicCache(key) → void
export function getPublicSnapshotCache()
export function setPublicSnapshotCache(snapshot)
export function getPublicContentDetailCache(slug)
export function setPublicContentDetailCache(slug, content)
export function clearPublicCmsCache()
```

### src\services\siteSettings.ts

```
export function extractGoogleDriveFileId(value)
export function normalizeGoogleDriveImageUrl(value)
export function extractIframeSrc(value) → string
export function normalizeSiteSettings(input) → SiteSettings
```

### src\services\users.ts

```
export interface UserAccountInput
  id?: string
  name: string
  email: string
  role: User["role"]
  status: UserAccount["status"]
  password?: string
export async function getUserAccounts() → Promise<UserAccount[]>
export async function authenticateUser(email, password) → Promise<UserAccount>
export async function saveUserAccount(input, actor?) → Promise<UserAccount>
export async function deleteUserAccount(id, actor?) → Promise<UserAccount[]>
export async function resetUserAccounts(actor?) → Promise<UserAccount[]>
```

### src\shared\components\ContentBlocksRenderer.tsx

```
component ContentBlocksRenderer
props ContentBlocksRendererProps
```

### src\shared\components\EmptyState.tsx

```
component EmptyState
props EmptyStateProps
```

### src\shared\components\VercelInsights.tsx

```
component VercelInsights
hook useRouterState
export VercelInsights
```

### src\shared\pages\NotFoundPage.tsx

```
component NotFoundPage
hook useNavigate
```

### src\styles.css

```
.table-scroll
.content-summary
```

### src\types.ts

```
export interface User
  id: string
  name: string
  email: string
  role: "admin" | "editor" | "viewer"
  avatarUrl?: string
export interface UserAccount
  status: "active" | "disabled"
  passwordHash?: string
  createdAt: string
  updatedAt: string
export interface Session
  user: User
  token: string
  expiresAt: string
export interface ContentItem
  id: string
  title: string
  slug: string
  type: ContentType
  status: ContentStatus
  owner: string
  summary: string
  body?: string
export interface MediaAsset
```

### src\utils\browserErrorFilters.ts

```
export function installBrowserErrorFilters()
```

### src\utils\calendar.ts

```
export function toLocalDateTimeInputValue(value?)
export function isEndDateTimeBeforeStart(startDateTime, endDateTime)
export function getCalendarDateRangeError(startDateTime, endDateTime)
```

### src\utils\contentBlocks.ts

```
export interface ParagraphContentBlock
  type: "paragraph"
  text: string
export interface HeadingContentBlock
  type: "heading"
  text: string
  level: 2 | 3 | 4
export interface QuoteContentBlock
  type: "quote"
  text: string
  citation: string
export interface ChecklistContentBlock
  type: "checklist"
  items: string[]
export interface MediaContentBlock
  type: "image" | "video"
  mediaId: string
  caption: string
export interface ButtonContentBlock
  type: "button"
  label: string
  href: string
  variant: "contained" | "outlined"
export interface DividerContentBlock
  type: "divider"
```

### src\utils\dateDisplay.ts

```
export function convertWordPressFormatToDayjs(format)
export function formatDisplayDate(value, settings?)
export function formatDisplayTime(value, settings?)
export function formatDisplayDateTime(value, settings?)
```

### src\utils\files.ts

```
export function readFileAsBase64(file) → Promise<string>
export function formatFileSize(size)
```

### src\utils\safeUrl.ts

```
export function normalizeSafeHref(value) → string
export function normalizeSafeResourceUrl(value) → string
```

### src\utils\seo.ts

```
export function buildDocumentTitle(title?, siteName?)
export function updateDocumentMetadata(input)
export function useDocumentMetadata(input)
```
