export interface Env {
  PUBLIC_API_ALLOWED_ORIGINS?: string;
  PUBLIC_ANALYTICS_ALLOWED_ORIGINS?: string;
  PUBLIC_API_VERSION?: string;
  ADMIN_WRITE_ALLOWED_ORIGINS?: string;
  CMS_AUTH_PROXY_SECRET?: string;
  CMS_MFA_ENCRYPTION_KEY?: string;
  CMS_MFA_ENCRYPTION_KEY_VERSION?: string;
  ENVIRONMENT?: string;
  ENV?: string;
  CF_PAGES_BRANCH?: string;
  DB?: D1Database;
  PUBLIC_SITE_VIEW_RATE_LIMITER?: RateLimit;
  PUBLIC_PRESENCE_RATE_LIMITER?: RateLimit;
  PUBLIC_CONTENT_VIEW_RATE_LIMITER?: RateLimit;
  CMS_AUTH_RATE_LIMITER?: RateLimit;
  ADMIN_API_RATE_LIMITER?: RateLimit;
}
