export interface Env {
  PUBLIC_API_ALLOWED_ORIGINS?: string;
  PUBLIC_API_VERSION?: string;
  ADMIN_WRITE_ALLOWED_ORIGINS?: string;
  ADMIN_WRITE_PREVIEW_ENABLED?: string;
  ADMIN_WRITE_AUTH_MODE?: string;
  ADMIN_WRITE_ACCESS_TEAM_DOMAIN?: string;
  ADMIN_WRITE_ACCESS_AUD?: string;
  ADMIN_WRITE_ALLOWED_EMAILS?: string;
  ADMIN_RBAC_ADMINS?: string;
  ADMIN_RBAC_EDITORS?: string;
  ADMIN_RBAC_VIEWERS?: string;
  ADMIN_WRITE_ACCESS_JWKS_JSON?: string;
  ADMIN_WRITE_SMOKE_ENABLED?: string;
  ADMIN_WRITE_SMOKE_TOKEN?: string;
  CMS_AUTH_ENABLED?: string;
  CMS_AUTH_PROXY_SECRET?: string;
  CMS_MFA_ENCRYPTION_KEY?: string;
  CMS_MFA_ENCRYPTION_KEY_VERSION?: string;
  ENVIRONMENT?: string;
  DB?: D1Database;
}
