// Vercel's Node function builder performs a second TypeScript compilation for files in /api.
// The production build prebundles the full SSR graph with Vite into plain ESM first so this
// boundary does not re-typecheck the application under a different compiler context.

// @ts-expect-error Generated by the Vercel build command before functions are bundled.
import { handleVercelPublicSsrRequest } from "../server-build/vercelSsr.js";
// @ts-expect-error Plain ESM server helper is bundled by the Vercel function builder.
import { handleFacebookOembedFetchRequest } from "../server/facebookOembed/handler.mjs";

export default {
  fetch(request: Request) {
    const requestUrl = new URL(request.url);
    if (requestUrl.searchParams.get("_rcatFacebookOembed") === "1") {
      return handleFacebookOembedFetchRequest(request);
    }

    return handleVercelPublicSsrRequest(request);
  }
};
